version: '3.9'

services:
  api-pipeline:
    build: .
    container_name: api-pipeline-app
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    # ports opcionales si tu app expone algún endpoint
    # - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py

# Volúmenes locales
volumes:
  output:
